// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAibMsaRBOI5eo7mBZjy3UJD28YV-AyFY',
    appId: '1:507311280782:web:8e6b16f0f6fa5e55f52fdf',
    messagingSenderId: '507311280782',
    projectId: 'my-spotify-project88',
    authDomain: 'my-spotify-project88.firebaseapp.com',
    storageBucket: 'my-spotify-project88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5NSrmC5tC-0xte7jLd4E-jTty3IdPX6U',
    appId: '1:507311280782:android:eedc87ab618bf8cbf52fdf',
    messagingSenderId: '507311280782',
    projectId: 'my-spotify-project88',
    storageBucket: 'my-spotify-project88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdvUoOEKZScDJMG6FTKtheWW5VH2pr6f8',
    appId: '1:507311280782:ios:6604a410d34405fbf52fdf',
    messagingSenderId: '507311280782',
    projectId: 'my-spotify-project88',
    storageBucket: 'my-spotify-project88.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdvUoOEKZScDJMG6FTKtheWW5VH2pr6f8',
    appId: '1:507311280782:ios:6604a410d34405fbf52fdf',
    messagingSenderId: '507311280782',
    projectId: 'my-spotify-project88',
    storageBucket: 'my-spotify-project88.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAibMsaRBOI5eo7mBZjy3UJD28YV-AyFY',
    appId: '1:507311280782:web:832272fa82fb1c64f52fdf',
    messagingSenderId: '507311280782',
    projectId: 'my-spotify-project88',
    authDomain: 'my-spotify-project88.firebaseapp.com',
    storageBucket: 'my-spotify-project88.firebasestorage.app',
  );
}
